steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/yiwu-scraper/yiwu-scraper', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/yiwu-scraper/yiwu-scraper']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'yiwu-scraper'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/yiwu-scraper/yiwu-scraper'
      - '--service-account'
      - 'yiwu-scraper@yiwu-automate.iam.gserviceaccount.com'
      - '--region'
      - 'asia-northeast1'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--task-timeout'
      - '3600s'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/yiwu-scraper/yiwu-scraper'

options:
  logging: CLOUD_LOGGING_ONLY
